ALTER TABLE vpn_nodes
    ADD COLUMN IF NOT EXISTS ssh_host TEXT,
    ADD COLUMN IF NOT EXISTS ssh_port INTEGER NOT NULL DEFAULT 22,
    ADD COLUMN IF NOT EXISTS ssh_user TEXT,
    ADD COLUMN IF NOT EXISTS ssh_password TEXT;
