# Generated by Django 5.1.11 on 2026-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="URL path, for example /how-it-works/ or /help/install/",
                max_length=220,
                unique=True,
            ),
        ),
    ]
