# Generated by Django 5.1.11 on 2026-04-01 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_page_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип поста',
                'verbose_name_plural': 'Типы постов',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='manual_posts',
            field=models.ManyToManyField(blank=True, related_name='manual_pages', to='blog.post'),
        ),
        migrations.AddField(
            model_name='page',
            name='post_categories',
            field=models.ManyToManyField(blank=True, related_name='pages', to='blog.category'),
        ),
        migrations.AddField(
            model_name='page',
            name='posts_enabled',
            field=models.BooleanField(default=False, help_text='Показывать на странице ленту постов ниже основного контента.'),
        ),
        migrations.AddField(
            model_name='page',
            name='posts_limit',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='page',
            name='posts_source',
            field=models.CharField(choices=[('all', 'Все посты'), ('types', 'По типам/категориям'), ('manual', 'Выбранные вручную')], default='all', max_length=16),
        ),
        migrations.AddField(
            model_name='page',
            name='posts_title',
            field=models.CharField(blank=True, default='Публикации', max_length=120),
        ),
        migrations.AddField(
            model_name='page',
            name='post_types',
            field=models.ManyToManyField(blank=True, related_name='pages', to='blog.posttype'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.posttype', verbose_name='Тип поста'),
        ),
    ]
