# Generated by Django 5.1.11 on 2026-04-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0004_vpnnode_vpnnodeclient"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.TextField()),
                ("subject", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "support_tickets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sender_role", models.TextField()),
                ("message_text", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "ticket",
                    models.ForeignKey(db_column="ticket_id", on_delete=django.db.models.deletion.DO_NOTHING, to="cabinet.supportticket"),
                ),
            ],
            options={
                "db_table": "support_messages",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="supportticket",
            name="user",
            field=models.ForeignKey(blank=True, db_column="user_id", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="cabinet.botuser"),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="sender_user",
            field=models.ForeignKey(blank=True, db_column="sender_user_id", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="cabinet.botuser"),
        ),
    ]
