# Generated by Django 5.1.11 on 2026-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0005_supportmessage_supportticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgeServer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
                ("public_host", models.TextField()),
                ("public_ip", models.TextField()),
                ("frontend_port", models.IntegerField()),
                ("healthcheck_host", models.TextField(blank=True, null=True)),
                ("healthcheck_port", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("is_primary", models.BooleanField()),
                ("accept_new_clients", models.BooleanField()),
                ("priority", models.IntegerField()),
                ("last_health_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_ok", models.BooleanField(blank=True, null=True)),
                ("last_health_error", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "edge_servers",
                "managed": False,
                "verbose_name": "HAProxy Edge",
                "verbose_name_plural": "HAProxy Edges",
            },
        ),
    ]
