# Generated by Django 5.1.11 on 2026-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_edgeserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNNodeLoadSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_active_subscriptions', models.IntegerField()),
                ('observed_enabled_clients', models.IntegerField()),
                ('total_traffic_bytes', models.BigIntegerField()),
                ('peak_concurrency', models.IntegerField()),
                ('probe_latency_ms', models.IntegerField(blank=True, null=True)),
                ('health_ok', models.BooleanField()),
                ('health_error', models.TextField(blank=True, null=True)),
                ('score_hint', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'VPN Node Load Snapshot',
                'verbose_name_plural': 'VPN Node Load Snapshots',
                'db_table': 'vpn_node_load_snapshots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VPNRebalanceDecision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision_kind', models.TextField()),
                ('assignment_source', models.TextField()),
                ('from_score', models.FloatField(blank=True, null=True)),
                ('to_score', models.FloatField(blank=True, null=True)),
                ('score_delta', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('dns_change_id', models.TextField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'VPN Rebalance Decision',
                'verbose_name_plural': 'VPN Rebalance Decisions',
                'db_table': 'vpn_rebalance_decisions',
                'managed': False,
            },
        ),
    ]
